=== lmcchli/vvs/mas/core/component/oldfiles/config/callmanager.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2006 sp2 U (http://www.altova.com) by Malin (Mobeon) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="configuration" nillable="false">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="callmanager"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="callmanager">
		<xs:complexType mixed="true">
			<xs:sequence>
				<xs:element ref="requiredoutboundaudiomedia"/>
				<xs:element ref="requiredoutboundvideomedia"/>
				<xs:element ref="responsecodemappings" minOccurs="0"/>
				<xs:element ref="remoteparty"/>
				<xs:element ref="siptimers" minOccurs="0"/>
				<xs:element ref="diagnoseservice" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="callnotacceptedtimer" type="callnotacceptedtimer" use="optional"/>
			<xs:attribute name="registerbackofftimer" type="registerbackofftimer" use="optional"/>
			<xs:attribute name="registerbeforeexpirationtime" type="registerbeforeexpirationtime" use="optional"/>
			<xs:attribute name="blacklisttimer" type="blacklisttimer" use="optional"/>
			<xs:attribute name="inboundaudiomedia" type="xs:string" use="required"/>
			<xs:attribute name="inboundvideomedia" type="xs:string" use="required"/>
			<xs:attribute name="ptime" type="xs:int" use="optional"/>
			<xs:attribute name="registeredname" type="letterdigitonlystring" use="optional"/>
			<xs:attribute name="defaultcalltype" type="calltype" use="optional"/>
			<xs:attribute name="outboundcallcallingparty" type="xs:string" use="required"/>
			<xs:attribute name="outboundcallconnecttimeout" type="callnotacceptedtimer" use="optional"/>
			<xs:attribute name="disconnectonsiptimeout" type="xs:boolean" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="calltype">
		<xs:restriction base="xs:string">
			<xs:enumeration value="voice"/>
			<xs:enumeration value="video"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="callnotacceptedtimer">
		<xs:restriction base="xs:positiveInteger">
			<xs:minInclusive value="1000"/>
			<xs:maxInclusive value="32000"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="registerbackofftimer">
		<xs:restriction base="xs:positiveInteger">
			<xs:minInclusive value="5000"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="registerbeforeexpirationtime">
		<xs:restriction base="xs:positiveInteger">
			<xs:minInclusive value="1000"/>
			<xs:maxInclusive value="30000"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="blacklisttimer">
		<xs:restriction base="xs:positiveInteger">
			<xs:minInclusive value="1000"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="diagnoseservice">
		<xs:complexType>
			<xs:attribute name="host" type="xs:string" use="optional"/>
			<xs:attribute name="port" type="xs:positiveInteger" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="siptimers">
		<xs:complexType>
			<xs:attribute name="t2" type="xs:positiveInteger" use="optional"/>
			<xs:attribute name="t4" type="xs:positiveInteger" use="optional"/>
			<xs:attribute name="timerb" type="xs:positiveInteger" use="optional"/>
			<xs:attribute name="timerc" type="xs:positiveInteger" use="optional"/>
			<xs:attribute name="timerd" type="xs:positiveInteger" use="optional"/>
			<xs:attribute name="timerf" type="xs:positiveInteger" use="optional"/>
			<xs:attribute name="timerh" type="xs:positiveInteger" use="optional"/>
			<xs:attribute name="timerj" type="xs:positiveInteger" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="requiredoutboundaudiomedia">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="mediatype" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="requiredoutboundvideomedia">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="mediatype" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="mediatype">
		<xs:complexType>
			<xs:attribute name="encoding" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="responsecodemappings">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="mapping" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="defaultnetworkstatuscode" type="networkstatuscode" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="mapping">
		<xs:complexType>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="sipresponsecodeintervals" type="sipresponsecodeintervals" use="required"/>
			<xs:attribute name="networkstatuscode" type="networkstatuscode" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="letterdigitonlystring">
		<xs:restriction base="xs:string">
			<xs:pattern value="([a-zA-Z0-9])*"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="sipresponsecodeintervals">
		<xs:restriction base="xs:string">
			<xs:pattern value="[3-6][0-9][0-9](-[3-6][0-9][0-9])?(,[3-6][0-9][0-9](-[3-6][0-9][0-9])?)*"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="networkstatuscode">
		<xs:restriction base="xs:positiveInteger">
			<xs:minInclusive value="601"/>
			<xs:maxInclusive value="634"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="remoteparty">
		<xs:complexType>
			<xs:choice>
				<xs:element ref="ssplist"/>
				<xs:element ref="phone"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="ssplist">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="address" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="phone">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="address"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="address">
		<xs:complexType>
			<xs:attribute name="host" type="xs:string" use="required"/>
			<xs:attribute name="port" type="xs:positiveInteger" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== lmcchli/vvs/mas/core/component/callmanager/callmanager.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:noNamespaceSchemaLocation="callmanager.xsd">
    <callmanager
            callnotacceptedtimer="5000"
            registerbackofftimer="120000"
            registerbeforeexpirationtime="5000"
            blacklisttimer="1000"
            inboundaudiomedia="pcmu"
            inboundvideomedia="h263"
            ptime="40"
            registeredname="mas"
            defaultcalltype="voice"
            outboundcallcallingparty=""
            outboundcallconnecttimeout="30000"
            disconnectonsiptimeout="true"
            sendprovisionalresponsesreliable="sdponly"
            supporttestinput="false"
            useragentwithphoneinsipuributnouserparameter="cisco,radvision,eyebeam,express talk,mirial"
            contacturioverride="">


        <requiredoutboundaudiomedia>
            <mediatype encoding="pcmu"></mediatype>
            <mediatype encoding="telephone-event"></mediatype>
        </requiredoutboundaudiomedia>

        <requiredoutboundvideomedia>
            <mediatype encoding="h263"></mediatype>
        </requiredoutboundvideomedia>

			<releasecausemappings defaultnetworkstatuscode="622">
				<mapping name="suppressed" networkstatuscode="614" sipresponsecodeintervals="600" q850causeintervals="17" q850locationintervals="0,1"/>
				<mapping name="busy" networkstatuscode="603" sipresponsecodeintervals="499" q850causeintervals="0,17" q850locationintervals="1-15"/>
				<mapping name="noreply" networkstatuscode="610" sipresponsecodeintervals="599,699" q850causeintervals="18-19"/>
				<mapping name="notreachable" networkstatuscode="613" sipresponsecodeintervals="301,403-404" q850causeintervals="1-9,20-23,25-31" q850locationintervals="1-2,5-6"/>
				<mapping name="test" networkstatuscode="620" sipresponsecodeintervals="503" q850causeintervals="39-44,46"/>
			</releasecausemappings>

        <remoteparty>
            <sipproxy>
                <address host="localhost" port="5090"/>
            </sipproxy>
        </remoteparty>

        <siptimers t2="8" t4="4" timerb="4" timerc="400" timerd="4" timerf="4" timerh="4" timerj="4"/>

        <diagnoseservice host="localhost" port="5080"/>

        <loadregulation
                initialramphwm="0"
                channelstoincrease="1"
                numberofincrements="1"/>

        <restrictedoutboundheaders>
        </restrictedoutboundheaders>





    </callmanager>
</configuration>

=== lmcchli/vvs/mas/core/component/callmanager/callmanager_with_ssps.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:noNamespaceSchemaLocation="callmanager.xsd">
    <callmanager
            registerbackofftimer="5000"
            registerbeforeexpirationtime="1000"
            registeredname=""
            inboundaudiomedia="pcmu"
            inboundvideomedia="h263"
            outboundcallcallingparty=""
            contacturioverride=""
            outboundcallconnecttimeout="30000"
            disconnectonsiptimeout="true">

            
            <requiredoutboundaudiomedia>
				<mediatype encoding="pcmu"></mediatype>
				<mediatype encoding="telephone-event"></mediatype>
			</requiredoutboundaudiomedia> 

            <requiredoutboundvideomedia>
				<mediatype encoding="h263"></mediatype>
			</requiredoutboundvideomedia> 

			<remoteparty>
				<ssplist>
					<address host="localhost" port="5090"/>
				</ssplist>
			</remoteparty>	

	</callmanager>
</configuration>
