=== lmcchli/vvs/mas/core/component/oldfiles/config/contenttypemapper.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="codec">
		<xs:complexType>
			<xs:attribute name="mimetype" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string"/>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="configuration">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="contenttypemapper"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="contenttype">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="codec" maxOccurs="unbounded"/>
				<xs:element ref="fileext"/>
			</xs:sequence>
			<xs:attribute name="mimetype" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string"/>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="contenttypemapper">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="contenttype" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="fileext">
		<xs:complexType>
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string"/>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== lmcchli/vvs/mas/core/component/oldfiles/config/contenttypemapper.xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="contenttypemapper.xsd">
	<contenttypemapper>	
		<contenttype mimetype="video/quicktime">
			<codec mimetype="video/h263"/>
			<codec mimetype="audio/pcmu"/>
			<fileext name="mov"/>
		</contenttype>
		<contenttype mimetype="audio/wav">
			<codec mimetype="audio/pcmu"/>
			<fileext name="wav"/>
		</contenttype>
		<contenttype mimetype="text/plain">
			<codec mimetype="text/plain"/>
			<fileext name="txt"/>
		</contenttype>
	</contenttypemapper>
</configuration>
